### ISSUE TITLE
Scripts not run on private window

### ISSUE THREAD

**Issue by LouCypher** [rlr/dotjs-addon#35]
STR:
just open private window and load a site that has custom script.

**Comment by mspreij** [comment]
No fixes? :-/ I would like this as well, possibly optionally.

**Comment by eridal** [comment]
Seems like we need to add this link to `package.json`

```json
"permissions": {"private-browsing": true}
```

https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing#Opting_into_private_browsing

**Comment by mspreij** [comment]
:+1: Yes please :-) I'm not familiar with manually building extensions (and https://jetpack.mozillalabs.com/sdk/latest/docs/ 404s?), but I'm patient..

**Comment by rlr** [comment]
^^ Landed fix. It will go out in next version

**Comment by rlr** [comment]
The new version has already been approved and released: https://addons.mozilla.org/en-US/firefox/addon/dotjs/

:balloon:

**Comment by mspreij** [comment]
\o/ thanks!
