### ISSUE TITLE
Firefox 34.0.5

### ISSUE THREAD

**Issue by zmtongit** [rlr/dotjs-addon#37]
Hi, I upgraded to new version of FF (to 34.0.5) and dotjs not working. Could you please help me?

THX

**Comment by cbdavide** [comment]
I'm running the 35.0 Firefox version, and it's working fine

**Comment by EvanHahn** [comment]
Firefox 41 is fine for me. Worth closing this issue?

**Comment by zmtongit** [comment]
I changed plugin to Greasemonkey (in 2014 :o))
