### ISSUE TITLE
Require paths change with latest FF versions

### ISSUE THREAD

**Issue by ralesi** [rlr/dotjs-addon#40]
I just set up dotjs on FF-41 and had to change a bit of the source to allow it to work.  i.e. `require('file')` doesn't work anymore, you need `require(/sdk/io/file')`.  

Should I submit the necessary changes as a patch or do we need to keep a separate branch for latest FF sdk?

**Comment by rlr** [comment]
You can submit the patch and I'll submit it to Addons.m.o specifying it is for FF 41+.

**Comment by rlr** [comment]
And thank you!

**Comment by rlr** [comment]
Fixed 881b256a111797a6c3157702a88bd7f7dccb2ebb
