### ISSUE TITLE
.dotjs is active!

### ISSUE THREAD

**Issue by eridal** [rlr/dotjs-addon#42]
Hi all,

I'm asking this as a a happy user of this addon.

It's been a while since last updated. 

What are the plans for the future?

**Comment by rlr** [comment]
Hmm. Define "live" :)

It's pretty much in maintenance mode. Fixing it when a new Firefox version breaks it. Other than that, I don't have any plans but I'd be open.

**Comment by eridal** [comment]
Hey, Nice to hear! and thanks for the quick answer!

I guess we can do small commits --maybe adding documentation-- like twice a month, so we can show at the main page that the project is active?

**Comment by rlr** [comment]
yeah true. It looks like I didnt update the changelog last release. oops

**Comment by rlr** [comment]
or maybe i did. But since then it was updated to work with the new addon tools (jpm). I need to play with that myself and update the docs. Also, I should be tagging releases. I fail.

**Comment by eridal** [comment]
Nah, that's ok. We all are learning. Don’t be hard on you :wink:
